<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tester-PC" failures="3" tests="31" name="com.mytest.FeesManager" time="72.756" errors="0" timestamp="17 Aug 2018 05:46:03 GMT" skipped="0">
  <testcase classname="com.mytest.FeesManager" name="Blank_NextdueDate_functionality" time="0.233"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Payment_Mode_Functionality" time="0.141"/>
  <testcase classname="com.mytest.FeesManager" name="Save_Changes_button_functionality" time="2.146"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_numbers" time="0.161"/>
  <testcase classname="com.mytest.FeesManager" name="Notes" time="0.246"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Payment_Fee_Status_functionality" time="0.429"/>
  <testcase classname="com.mytest.FeesManager" name="Update_Fee_Receipt" time="4.783"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Notes" time="0.194"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Payment_Clear" time="0.163"/>
  <testcase classname="com.mytest.FeesManager" name="NextdueDate_functionality" time="3.749"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_aplhabets" time="0.392"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_whitespaces_at_begining" time="0.209"/>
  <testcase classname="com.mytest.FeesManager" name="Add_Admission" time="24.314"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_whitespaces" time="0.396"/>
  <testcase classname="com.mytest.FeesManager" name="Blank_Fee_Refund" time="3.341"/>
  <testcase classname="com.mytest.FeesManager" name="Payment_Mode_Functionality" time="0.180"/>
  <testcase classname="com.mytest.FeesManager" name="Delete_Fee_Receipt" time="8.686"/>
  <testcase classname="com.mytest.FeesManager" name="Payment_Clear" time="0.203"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_whitespaces" time="0.204"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_special_characters" time="0.404">
    <failure message="Now Receiving field contain alphabets expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Now Receiving field contain alphabets expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.mytest.FeesManager.Now_Receiving_contains_special_characters(FeesManager.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Now_Receiving_contains_special_characters -->
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Fee_Status_functionality" time="0.382">
    <failure message="Due Date NOT Getting Saved expected [10/10/2018] but found [NA]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Due Date NOT Getting Saved expected [10/10/2018] but found [NA]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.mytest.FeesManager.Fee_Refund_Fee_Status_functionality(FeesManager.java:400)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Fee_Refund_Fee_Status_functionality -->
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_special_characters" time="0.411">
    <failure message="Fee Refund field contain alphabets expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Fee Refund field contain alphabets expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.mytest.FeesManager.Fee_Refund_contains_special_characters(FeesManager.java:302)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Fee_Refund_contains_special_characters -->
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Save_Changes_button_functionality" time="2.105"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_Update_Fee_Receipt" time="6.360"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_whitespaces_at_begining" time="0.286"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_lessthan_Paid_Fees" time="1.280"/>
  <testcase classname="com.mytest.FeesManager" name="Now_Receiving_contains_numbers" time="0.283"/>
  <testcase classname="com.mytest.FeesManager" name="Blank_Now_Receiving_Field" time="7.617"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_View_Receipts" time="1.489"/>
  <testcase classname="com.mytest.FeesManager" name="View_Receipts_functionality" time="1.795"/>
  <testcase classname="com.mytest.FeesManager" name="Fee_Refund_contains_aplhabets" time="0.174"/>
</testsuite> <!-- com.mytest.FeesManager -->
