<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tester-PC" failures="1" tests="2" name="com.mytest.Receipt_Day_Book_Report" time="24.007" errors="0" timestamp="10 Aug 2018 09:22:45 GMT" skipped="0">
  <testcase classname="com.mytest.Receipt_Day_Book_Report" name="Add_Account_Head" time="12.353"/>
  <testcase classname="com.mytest.Receipt_Day_Book_Report" name="Cash_Payment_Mode" time="11.654">
    <failure message="Transaction Date NOT Getting Saved expected [10/08/2018] but found [Loading data from server]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Transaction Date NOT Getting Saved expected [10/08/2018] but found [Loading data from server]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.mytest.Receipt_Day_Book_Report.Cash_Payment_Mode(Receipt_Day_Book_Report.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Cash_Payment_Mode -->
</testsuite> <!-- com.mytest.Receipt_Day_Book_Report -->
