<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tester-PC" failures="1" tests="12" name="com.mytest.Trainer_Batch" time="44.552" errors="0" timestamp="18 Aug 2018 05:13:14 GMT" skipped="0">
  <testcase classname="com.mytest.Trainer_Batch" name="Incentive_contain_numbers" time="0.192"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Incentive_contain_negative_numbers" time="0.359">
    <failure message="Incentive Contains Negative Numbers expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Incentive Contains Negative Numbers expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.mytest.Trainer_Batch.Incentive_contain_negative_numbers(Trainer_Batch.java:152)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Incentive_contain_negative_numbers -->
  <testcase classname="com.mytest.Trainer_Batch" name="Incentive_contain_special_characters" time="0.584"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Blank_Course" time="0.091"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Checkbox" time="4.670"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Add_Employee" time="27.578"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Incentive_contain_whitespaces_at_begining" time="0.201"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Trainer" time="0.284"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Course" time="0.276"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Incentive_contain_alphabets" time="0.171"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Blank_Trainer" time="9.967"/>
  <testcase classname="com.mytest.Trainer_Batch" name="Incentive_contain_whitespaces" time="0.179"/>
</testsuite> <!-- com.mytest.Trainer_Batch -->
